apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app.kubernetes.io/name: django-config
    app.kubernetes.io/env: dev
    app.kubernetes.io/owner: SergeyPavlov
data:
  SECRET_KEY: "5zb0%xls*s#4rlgs4(=khay%oo9$$)z2=sig6k0_*"
  ALLOWED_HOSTS: "192.168.59.100,192.168.59.101,star-burger.test"
  DATABASE_URL: "postgres://test_k8s:OwOtBep9Frut@192.168.1.72:5432/test_k8s"
  DEBUG: "False"
  