apiVersion: v1
kind: Service
metadata:
  name: django-app
  labels:
    name: django-service
    env: dev
    owner: SergeyPavlov
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  externalIPs:
    - xx.xx.xx.xx
  
