apiVersion: v1
kind: Pod
metadata:
  name: cleaner
  labels:
    app: cleaner
spec:
  containers:
    - name: cleaner
      image: spawlov/django-app:latest
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: django-config
      command:
        - ./manage.py
        - clearsessions
  restartPolicy: Never
  