apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: spawlov/django-app:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: django-app-config
          ports:
            - containerPort: 80
              name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: django-app-autoscaling
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: django-app
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: django-app
  labels:
    env: dev
    owner: SergeyPavlov
spec:
  selector:
    app: django
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 192.168.59.101
