apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  labels:
    env: dev
    app: webserver
    tier: frontend
    owner: SergeyPavlov
spec:
  containers:
    - name: container-nginx
      image: nginx:latest
      ports:
        - containerPort: 80